baseURL: https://fnof.github.io
languageCode: en-us
defaultContentLanguage: en
title: Fnof
theme: papercss-hugo-theme

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

imaging:
  quality: 99

# To disable, set to an extremely large value, such as 999999
paginate: 5

params:
  homeMetaContent: A Hugo theme made with PaperCSS, the less formal CSS framework.
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: Jan 2, 2006
  navTitleLink: /

menu:
  nav:
    - name: Posts
      url: /
      weight: 1
    - name: Tags
      url: /tags/
      weight: 2

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: true
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
